### ISSUE TITLE
filling "from-date" fails

### ISSUE THREAD

**Issue by mike-landl** [ChristianKoplenig/SMIT#6]
Currently the code does not work for me because during the webscraping in the function [stromnetz_fillTageswerte](https://github.com/tmpck/strom/blob/main/modules/scrapedata.py#L103C122-L103C122) the selection of the *from-date* selects the month instead of the day. As a result the filling of the data field does not work as intended and the script times out.

![from-date](https://github.com/tmpck/strom/assets/13545527/294ddc8f-13f7-44dc-aaa3-2af0d09bf350)

**Comment by ChristianKoplenig** [comment]
This should be fixed with #99
