### ISSUE TITLE
Rework requirements.txt

### ISSUE THREAD

**Issue by ChristianKoplenig** [ChristianKoplenig/SMIT#81]
Dependencies maybe to strict. Investigate how to adjust dependencies for other (3.9,...) python versions.

**Comment by mike-landl** [comment]
As a first step I used https://github.com/bndr/pipreqs to generate shorter version of the requirements.
It came up with:

```
-e .
matplotlib==3.8.0
pandas==2.1.0
pytest==7.4.2
rsa==4.9
seaborn==0.12.2
selenium==4.12.0
setuptools==65.5.0
tomlkit==0.12.1
```

Additionally I think we need for testing:

```
tox==4.10.0
pytest==7.4.0
```

Those are currently unused, but they might be needed in the future for testing:

```
pytest-cov==4.0.0
flake8==6.1.0
mypy==1.5.1
```

**Comment by mike-landl** [comment]
But this is only for python 3.11, would also need to check python 3.9, 3.10 if those versions are available for those older python version

**Comment by ChristianKoplenig** [comment]
I changed the requirements now to the simple version generated by pipreg. Tested it in a container setup and with cloning into a new venv. See commit: 0d66e9702f894e72a1565f72d51d3bdb8ae1131d
