### ISSUE TITLE
Add installation / usage instructions for windows

### ISSUE THREAD

**Issue by mike-landl** [ChristianKoplenig/SMIT#87]
My current workflow are the following commands (using windows powershell):

```powershell
git clone https://github.com/ChristianKoplenig/SMIT.git
cd SMIT
python -m venv .venv
.\.venv\Scripts\Activate.ps1
python -m pip install --editable .
```

Next I need to download geckodriver from https://github.com/mozilla/geckodriver/releases and place it in the root location of the repository.
Finally I have to modify the `config/user_settings.toml` file and change the geckodriver_executable path to './geckodriver.exe'

**Comment by ChristianKoplenig** [comment]
With #99 the app framework completely changed. The geckodriver location issue should be fixed now. For issues with the new framework I would prefer opening a new issue.
